- name: Create GCP Firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Firewall rules
      google.cloud.gcp_compute_firewall:
        name: "{{ machine_name }}s-fw"
        direction: INGRESS
        source_ranges:
          - "{{ansible_server_ip}}"
        allowed:
          - ip_protocol: tcp
            ports:
              - '15672'
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present