version: '2'

networks:
  rabbit-net:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    container_name: 'rabbitmq'
    # @todo: Fill in from variables
    environment:
      RABBITMQ_DEFAULT_USER: test-user
      RABBITMQ_DEFAULT_PASS: test-user
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-net